version: '3.8'
services:
  neo4j:
    image: graphstack/dozerdb:5.18.1
    container_name: neo4j-server
    ports:
      - "7474:7474"
      - "7687:7687"
    user: "${UID}:${GID}"
    environment:
      - NEO4J_dbms_connector_https_advertised__address=localhost:7473
      - NEO4J_dbms_connector_http_advertised__address=localhost:7474
      - NEO4J_dbms_connector_bolt_advertised__address=localhost:7687
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc", "n10s"]
      - NEO4J_dbms_memory_transaction_total_max=0
      - NEO4J_dbms_unmanaged__extension__classes=n10s_endpoint=/rdf
    volumes:
      - ./mount/neo4j/data:/data
      - ./mount/neo4j/import:/var/lib/neo4j/import
      - ./mount/neo4j/plugins:/plugins
